### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by tianheng2017** [Loopring/protocol#259]
Compilation warnings encountered:

zeppelin-solidity/contracts/token/StandardToken.sol:73:3: Warning: No visibility specified. Defaulting to "public".
  function increaseApproval (address _spender, uint _addedValue)
  ^
Spanning multiple lines.
,zeppelin-solidity/contracts/token/StandardToken.sol:80:3: Warning: No visibility specified. Defaulting to "public".
  function decreaseApproval (address _spender, uint _subtractedValue)
  ^
Spanning multiple lines.
,zeppelin-solidity/contracts/ownership/Ownable.sol:20:3: Warning: No visibility specified. Defaulting to "public".
  function Ownable() {
  ^
Spanning multiple lines.
,zeppelin-solidity/contracts/math/SafeMath.sol:9:3: Warning: Function state mutability can be restricted to pure
  function mul(uint256 a, uint256 b) internal constant returns (uint256) {
  ^
Spanning multiple lines.
,zeppelin-solidity/contracts/math/SafeMath.sol:15:3: Warning: Function state mutability can be restricted to pure
  function div(uint256 a, uint256 b) internal constant returns (uint256) {
  ^
Spanning multiple lines.
,zeppelin-solidity/contracts/math/SafeMath.sol:22:3: Warning: Function state mutability can be restricted to pure
  function sub(uint256 a, uint256 b) internal constant returns (uint256) {
  ^
Spanning multiple lines.
,zeppelin-solidity/contracts/math/SafeMath.sol:27:3: Warning: Function state mutability can be restricted to pure
  function add(uint256 a, uint256 b) internal constant returns (uint256) {
  ^
Spanning multiple lines.

Writing artifacts to ./build/contracts

**Comment by tianheng2017** [comment]
/Users/administrator/Downloads/protocol-master/contracts/LoopringProtocolImpl.sol:396:34: DeclarationError: Undeclared identifier.
        address _feeRecepient = (feeRecepient != 0x0) ? feeRecepient : ringminer;
                                 ^----------^
Compilation failed. See above.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! loopring-smart-contracts@1.0.0 compile: `rm -rf build/contracts && truffle compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the loopring-smart-contracts@1.0.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/administrator/.npm/_logs/2018-01-31T04_05_48_009Z-debug.log

**Comment by kongliangzhong** [comment]
Sorry, we are working on branch version1.1 now, so maybe some code not merged to master branch.  
I will fix this soon

**Comment by kongliangzhong** [comment]
fixed.
